openapi.go, serve.go
=> Generate openapi schema in separate goroutine

options.go
=> feat: allow users to avoid logging

ctx.go, deserialization.go, deserialization_test.go, errors.go, errors_test.go, examples/simple-crud/errors_custom.go, examples/simple-crud/store/ingredient.go, examples/simple-crud/views/admin.go, middleware/basicauth/basicauth.go, options_test.go, serialization.go, serialization_test.go
=> Validation should return 400 on fail

documentation/docs/guides/middlewares.md
=> Doc: Fix usage of `Use` for middleware example

README.md, documentation/docs/guides/openapi.md, examples/basic/main.go, examples/full-app-gourmet/controller/recipe.go, examples/full-app-gourmet/controller/routes.go, examples/full-app-gourmet/views/views.go, examples/openapi/main.go, go.work, mux.go, mux_test.go, openapi_operations.go, openapi_operations_test.go, options.go
Uses the same underlying `Param` method
=> renamed AddHeader, AddCookie, WithQueryParams to Header, Cookie, QueryParam

documentation/docs/guides/options.md, options.go, serve.go
- CORS special middleware handling
- CORS documentation
Fixes #59
=> cors handling

ctx.go, deserialization.go, errors.go, errors_test.go, middleware/basicauth/basicauth.go, options_test.go, serialization.go, serialization_test.go, serve_test.go, validation.go, validation_test.go
Implementing RFC 9457
Fixes #81, closes #32
=> RFC 9457 implementation

.gitignore, mux.go, mux_test.go, openapi.go, options.go, options_test.go
closes #62 
Thanks @dylanhitt! I've just added a few tests on tag inheritance to make sure all is well.
The more tests, the stronger Fuego gets!
=> feat: add tags to the Server (i.e Group) level

deserialization_test.go
Found this while playing with something on my fork.
Cheers
=> chore: fix fault ReadYAML test

cmd/fuego/commands/controller.go, cmd/fuego/commands/controller_test.go
Thank you @minpeter for the PR !
I removed the `--output` option and fixed the tests.
=> Cli controller path

ctx.go, ctx_test.go, deserialization.go, deserialization_test.go, options_test.go
Add the ability to read XML from body.
I elected not to duplicate all the same test that is there for json i.e transform readtwice etc as it's covered pretty well. If you want that for this let me know.
=> feat: add the ability to read xml from body

ctx_test.go
1. Add the test form yaml context body
2. Noticed that some of these were in the wrong order
Also this is based on the xml PR #99 
Cheers
=> Chore: add yaml context test

examples/full-app-gourmet/server/server.go, examples/full-app-gourmet/views/views.go, mux.go, mux_test.go, openapi.go, openapi_operations.go, openapi_operations_test.go, security_test.go, serve.go, serve_test.go
closes #71 
All fields (ID...) are not currently implemented
=> Struct-Based route Registration

options.go
=> chore: deprecation notice for WithPort()

options_test.go
=> chore: typo on TestWithoutStartupMessages test

Makefile, examples/petstore/controllers/pets.go, examples/petstore/controllers/pets_test.go, examples/petstore/lib/server.go, examples/petstore/lib/server_test.go, examples/petstore/lib/testdata/doc/openapi.golden.json, examples/petstore/main.go, examples/petstore/models/Pet.go, examples/petstore/services/in_memory_pets.go, examples/petstore/services/in_memory_pets_test.go, examples/petstore/testdata/doc/openapi.golden.json, openapi.go, openapi_test.go, options.go
Parses struct fields
- description => description
- example => example
- json => nullable (if contains omitempty)
- validate:
- required => required
- min=1 => min=1 (for integers)
- min=1 => minLength=1 (for strings)
- max=100 => max=100 (for integers)
- max=100 => maxLength=100 (for strings)
Please see the golden file for OpenAPI changes :)
=> Info fields

deserialization_test.go
Ensure we hit the test case when getting EOF in read. If we're gonna go with the validation error (instead of an EOF or request body is empty) here per the example:
```json
{
"title": "Validation Error",
"status": 400,
"detail": "Name is required",
"errors": [
{
"name": "MyInput.Name",
"reason": "Key: 'MyInput.Name' Error:Field validation for 'Name' failed on the 'required' tag",
"more": {
"field": "Name",
"nsField": "MyInput.Name",
"param": "",
"tag": "required",
"value": ""
}
}
]
}
```
I don't really have a preference on the response, but want to ensure we're testing the clause well. I can add to all Send* funcs in the test suite as well.
=> chore: ensure we test EOF clause in read

ctx.go, ctx_test.go
Related issue: https://github.com/go-fuego/fuego/issues/167
=> Enhance query parameters to support a list of parameters

deserialization_test.go, serialization_test.go
Per: https://github.com/go-fuego/fuego/pull/164#discussion_r1727986571
=> chore: add test for SendHTML and minor test cleanup

cmd/fuego/commands/controller.go, cmd/fuego/templates/controller/controller.go
=> Fix package name for Generated Controllers

mux.go, option/option.go, option/option_test.go
@dylanhitt for reference.
I'm merging this as it is a really small PR
=> Hide route from OpenAPI spec, variadic options way

openapi.go, openapi_test.go
=> fixed wrong schema generation when using embedded struct

CONTRIBUTING.md, errors.go, errors_test.go, serve_test.go, validation_test.go
- **feat: add 500 error (#194)**
- **InternalServerError is an HTTPError with more explicit status code**
=> 500 internal server error

examples/full-app-gourmet/store/queries/recipe.sql, examples/full-app-gourmet/store/recipe.sql.go, examples/full-app-gourmet/templa/admin/ingredient.page.templ, examples/full-app-gourmet/templa/admin/recipe.form.templ, examples/full-app-gourmet/templa/admin/recipe.new.templ, examples/full-app-gourmet/templa/admin/recipe.page.templ, examples/full-app-gourmet/templates/pages/admin/single-recipe.page.html, examples/full-app-gourmet/views/admin.ingredient.go, examples/full-app-gourmet/views/admin.recipe.go, examples/full-app-gourmet/views/views.go
Did the minimum to get this going. 
I'll probably open up a few more PRs as it's a nice opportunity to familiarize myself with htmx/some other aspects of web development I don't really get to touch anymore day to day.
I elected to just have the `hx-trigger` be on button save press until I figure out something that feels a bit better for dynamic editing on just `change`.
closes #191
Feel free to provide some guidance if this wasn't the initial intention.
=> fix: gourmet app admin recipe creation

examples/petstore/controllers/pets.go, examples/petstore/controllers/pets_test.go, examples/petstore/lib/testdata/doc/openapi.golden.json, mux.go, openapi.go, option.go, option/option.go, option_test.go, serve.go
Adds a default status code in the server code and in the OpenAPI Description
=> Default status code

option.go, option/option.go, option_test.go, serve_test.go, server.go
Some cleanup suggest by @ccoVeille in #274
=> chore: cleanup some status codes and godoc

option_test.go, serve.go
=> Set status code before returning when no data

examples/petstore/lib/testdata/doc/openapi.golden.json, examples/petstore/models/Pet.go, openapi.go, openapi_test.go
closes #318 
@ccoVeille Mind taking a look.
=> fix: nested struct tags should be respected in openapi spec

examples/petstore/controllers/pets.go, examples/petstore/controllers/pets_test.go, examples/petstore/lib/testdata/doc/openapi.golden.json, examples/petstore/models/Pet.go, generics_test.go, openapi.go
=> Fixes generic return type support

engine.go, engine_test.go
I added shortcut option to disable engine error handler.
It fixes #326
=> feat: add disable error handler as engine option

README.md, documentation/docs/guides/errors.md, documentation/docs/guides/openapi.md, documentation/docs/guides/options.md, documentation/docs/guides/serialization.md, documentation/docs/guides/transformation.md, documentation/docs/guides/validation.md, documentation/docs/tutorials/rendering/index.md, mdsf.json
- **chore: format documentation with mdsf**
- **ci: add mdsf config file for future uses**
Here is the tool I used https://github.com/hougesen/mdsf
cc @hougesen
=> format Markdown fenced code blocks with mdsf

extra/fuegoecho/adaptor.go
Allows using the package for echo Groups.
@dylanhitt I'm currently migrating a 5 years old Echo (100+ routes) app to Fuego with the `fuegoecho` package 🔥 
Good thing to test edges of our new routers support.
=> Use an interface for the echo router in the fuegoecho package

engine_test.go
close #322 
kindly review @EwenQuim kindly review :)
=> fix: custom error addition should handle edge cases

net_http_mux.go, option_test.go, param_test.go
Duplicate of #324 with less library code changes and more tests.
Fixes #266 
FYI @ekumamatthew
=> Removes hardcoded Accept header from registerFuegoController

engine.go, extra/fuegoecho/adaptor.go, extra/fuegogin/adaptor.go, generic_mux.go, net_http_mux.go, openapi.go, openapi_handler_test.go, openapi_operations_test.go, option_test.go, route.go, server.go, server_test.go
=> feat: Middleware declaration customized

security.go, security_test.go
Instead of sentinel errors that don't compose well with fuego (they are not registered as HTTP errors with status code etc...)
=> Used `fuego.HTTPError` variants in the Security package

.golangci.yml, serialization.go, serialization_test.go
- Adds a unconvert
- A bit of code cleanup
=> Adds unconvert

net_http_mux.go
Added `Options` and `OptionsStd` methods analogous to the other http verbs
See #428
=> feat: added options methods

generics_test.go, validation.go
=> Accepts list as input in the body of the request

extra/fuegogin/adaptor.go
Adding convenience functions for the rest of the HTTP methods
=> add missing fuegogin methods

.github/CODEOWNERS
To be automatically added to reviewers for each PR :) 
If you don't like the concept or want/don't want to be tagged to a specific panel of files, don't hesitate to tell me!
=> Codeowners file

Makefile, ctx.go, deserialization.go, mock_context.go, server.go
Bumped golangci-lint. 
I did change ctx cause of the importShadow complaint. Not really sure what to change the other values too as the names are very appropriate. Do we want to disable that check maybe?
=> chore: bump golangci-lint version

examples/petstore/lib/testdata/doc/openapi.golden.json, openapi.go
=> feat: Parse tags for arrays/slices fields in structs

.github/workflows/go.yml
=> use go-version-file

.github/workflows/go.yml, .github/workflows/lint.yml
Security tab has been bugging me
=> ci: update github workflow perms
