README.md, ctx.go, deserialization.go, deserialization_test.go, examples/basic/main.go, examples/simple-crud/controller/ingredient.go, examples/simple-crud/store/dosing.go, examples/simple-crud/store/ingredient.go, examples/simple-crud/store/recipe.go
`OutTransformer` supports it, there's no reason no to support it.
It allows the user many options during the validation process.
=> Supports context in InTransformer

.github/workflows/go.yml
I noticed the testing ci/cd pipeline is using go version **1.21**.
Both go.mod and go.work target go version **1.22**.
I just thought the project should be tested using the same version as it targets.
Feel free to close the PR if you think this is incorrect.
Cheers! 🚀
=> Update ci/cd go version to 1.22

openapi_handler.go
Thank you for the fantastic work your team has done. When I use fuego for a demo, I noticed that the documentation does not display correctly on my extended screen, as follows:
I found a solution on the Stoplight documentation website that suggests resolving the issue by adding a style configuration to the body.
```html
<body style="height: 100vh;">
<stoplight-api />
</body>
```
[Stoplight Layout](https://docs.stoplight.io/docs/elements/d536b917a4e1d-layout)
Hope this issue can be fixed!
=> fix: Set body height to 100% of the viewport height

options.go, options_test.go
This pull request adds WithValidator option to Server which replaces default validator.
=> feat: add option for custom validator

ctx.go, deserialization.go, deserialization_test.go
The following adds the ability to submit yaml as a content type to be decoded ContextWithBody. I'm not quite sure if I did this probably as this comment [is throwing me off but it could just be a mistake?](https://github.com/go-fuego/fuego/commit/3bb79ad6313b8b81a4d9c96ad07954648ebf978f#diff-c4dd82978a1a49bcd620aff72208bbd8114f09341d701e188c247ce3e3511117R104)
Anyhow let me know your thoughts. I'm open to changing things up if this doesn't suffice. If there isn't any interest let me know as well. 
The pattern I chose here seems like it could be extended to XML easily as well.
=> feat: support decoding x-yaml content-type in ContextWithBody

ctx.go
Found this and tripped me up today as it seemed like the usage of ContextWithBody was on it's way to being deprecated with the current language that is there.
=> docs: ContextWithBody clarification

README.md, examples/basic/main.go, openapi.go, options.go, options_test.go, serve.go
This PR adds the option `WithAddr` to the server, which lets you specify the full "host:port" for the server to be run at. The `WithPort` func currently allows you to do this, but it's not obvious that you can. I believe it's better to be explicit about this, hence the addition.
With this change I've also deprecated `WithPort` but kept it for backwards compatibility. Up to you how you want to do it. One case that is not covered is if `WithPort` has been used to provide the complete addr: `WithAddr(localhost:8080)`.
I've also updated the log rows and the example in the README.
What do you think?
=> add WithAddr option, adjusted WithPort func to only handle port

openapi.go, openapi_test.go, options.go, options_test.go, serve.go
=> Exposes OutputOpenAPISpec method to generate directly the outputs without starting server

documentation/docs/guides/openapi.md, mux.go, mux_test.go, openapi.go, options.go
Added being able to hide routes from the server, by using server.Hide()
Implements server.Hide() from #60
=> Hide from Openapi Spec

ctx.go, documentation/docs/guides/controllers.mdx, documentation/docs/guides/openapi.md, middleware/cache/cache_test.go, mux_test.go
This adds more documentation and intuitive methods to get and set headers and cookies.
Fixes #79
=> Adds Cookie and Header methods to context

serialization.go, tests_test.go
When returning `UnauthorizedError`, returns the `application/problem+json` Content-Type header.
When returning any `error`, returns the `application/json` Content-Type header.
Fixes #87
=> Fixes error Content-Type

mux.go, mux_test.go, options.go, options_test.go
Closes #62 
I put the test where I thought they made sense the most. I added a test for `TestRegister` to specifically ensure routes have the last say. Let me know what you think. Happy to move things around, but I believe I have most things covered. 
Cheers
=> feat: add tags to the Server (i.e Group) level

cmd/fuego/commands/controller.go
Hello, I just found out about fuego.
While following the tutorial, I discovered that the operation of the `fuego controller` command was strange.
1. Run fuego controller books
2. Create controllers folder
3. Create books.go in the root, not the controllers folder.
This resulted in me having to manually move the files into the controllers folder.
This has been corrected.
fyi: I don't know why the --output option exists. Please let me know if you think it is unnecessary
thanks :)
=> fix: fuego controller command

mux.go, mux_test.go
closes #98 
Here's the fix. I'll get the tests up soon. Currently need this to get through the work day. 
Thanks
=> Draft: fix: middleware ordering

ctx.go, examples/full-app-gourmet/views/admin.ingredient.go
Fuego ContextXxx are valid [context.Context](https://pkg.go.dev/context#Context). It is of course based on [the standard library](https://pkg.go.dev/net/http#Request.Context)
=> Fuego Context is std lib context

openapi.go, openapi_test.go, options.go, options_test.go
Provide the ability to pretty print to the .json file
Bit of a vanity thing, but I have some colleagues asking for it. What does make this nice is that it provides the ability to pretty print in CI and we can place the file into a npm package (that's generated from the spec) to be consumed by downstream API users. It also makes diffs useful source control managers.
=> feat: add option to pretty print json doc output

mux.go, mux_test.go
When using the FullName you end up with some pretty gnarly function name when generating clientSDKs 
```
type PATCHv2devicesNamedeallocateGitlabComdylanhittmyprojpkgapiserverv2handlerHandlerRequesBody
```
I realized it's possible to override this but our default should be a bit more organized.
Let me know what you think.
=> fix: revert back to the simple funcName style operationID

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/lint.yaml, .markdownlint.yaml, Makefile, README.md, documentation/README.md
Closes #143
@ccoVeille thank you for the suggestions. The practice actually uncovered that the CI wasn't actually testing anything 😅. I appreciate your time here.
Let me know how this looks!
Cheers
=> chore: add justification for disabled markdownlint rules

openapi.go, openapi_test.go
This did turn out to be pretty complex. 
The following is by no means finished. More looking for a discussion. If you take a look #133 the bug is fairly clear. We do not respect response nor return types when they are arrays. 
The only way I can think of solving this is that we must create the ref to the schema and link it at the bottom of a recursion tree. If you do not do this you will end up with improper refs, with the original approach the input for the first type wins so if an array of `MyStruct` is passed the schema will be a list of `MyStruct` rather than just the simple Schema of `MyStruct`. See `schemaDive`. Currently this does require us to dive twice on request bodies. Since we seem to check request bodies if they are `unknown-type`/`string`, which I am unsure why (wouldn't we …
=> fix: differentiate between array types and standard structs

deserialization.go, deserialization_test.go
Related issue: https://github.com/go-fuego/fuego/issues/166
=> Fixing EOF bad request error when consume a route with empty request body

examples/petstore/controllers/pets.go, examples/petstore/lib/testdata/doc/openapi.golden.json, openapi.go, openapi_operations.go, openapi_operations_test.go, serve_test.go
closes #159
Provides the ability for the user to explicitly
set what content types and request body can be.
Maintains the defaullt of `application/json` and `application/xml`
=> feat: add route.RequestContentType

cmd/fuego/templates/controller/controller.go
While doing the other PR #178, I noticed a typo in the word `Resources`. I am not sure if it was intentional, but I have fixed it in this PR. If it was intentional, feel free to close this PR.
=> Fix (potential) typo in the word resources

errors.go
Closes #180 
Call the `StatusCode` function instead of passing it as a pointer.
=> Correctly log status code

.golangci.yml, openapi.go
Issue: https://github.com/go-fuego/fuego/issues/188
Fix: Added `misspell` flag to the `golangci-lint`. 
Sample output
Link to the details of the flag: https://golangci-lint.run/usage/linters/#misspell
=> fix: enabled misspell flag to golangci-lint to detect typos

mux.go, option/option.go, option/option_test.go, options.go, options_test.go
closes #197 
Figured it was better to do this in the `BaseRoute` than and if statement in the `RegisterOpenAPIOperation`. I think we should strive to always limit the complexity in `RegisterOpenAPIOperation`.
Cheers!
=> feat: add WithRequestContentType config option for the Server

errors.go, examples/petstore/lib/testdata/doc/openapi.golden.json, mux.go, options_test.go, serialization.go, serialization_test.go
This PR does 2 things:
- explicitely declare te Accept Header that we use in Fuego, I don't know why I didn't do it earlier
- Treat serialization errors as a 406 Not Acceptable error
=> Better Accept Serialization

openapi.go, options.go
fixes #201
To prevent data races when creating multiple instances of `fuego.Server` in tests for example. I moved the `openapi3gen.Generator` package global to the `fuego.Server` struct. 
Hopefully that make sense.
=> Fix data race due to global instance of openapi3gen.Generator

mux.go, mux_test.go, openapi.go, openapi_operations.go, openapi_operations_test.go, option.go, server.go
Removes deprecated params.
Also fixes the behaviour of `OptionAddError` that was replaced by the global error. We didn't see it when switching to variadic options because the test wasn't made.
=> Remove deprecated params

documentation/docs/guides/openapi.md, examples/petstore/lib/testdata/doc/openapi.golden.json, mux.go, mux_test.go, openapi.go, openapi_test.go, option.go, option/option.go, server.go, server_test.go
Implemented https://github.com/go-fuego/fuego/pull/254#discussion_r1873450220.
Enables to not only inherit param, but all options!
Might enable interesting features in the future.
Makes `WithGlobalResponseTypes` obsolete in favor of stacking a `option.AddError` in the global `WithRouteOptions`
=> Refactor route option inheritance

mux.go, mux_test.go
When a group is created with an empty path, the tag should not be added to the route.
=> feat: Prevents empty tags from being added to routes

mux.go, option.go, server.go
Instead of referencing the main router and only use OpenAPI field...
Allows to access to the OpenAPI instead of relying on a private net/http server reference that made no sense. Allows progress for #260 
Loving where all this goes, it's getting cleaner and works better.
=> Adds a direct reference to the OpenAPI object in the BaseRoute object

openapi.go, serve.go, server.go
Closes #248 
Will conflict with https://github.com/go-fuego/fuego/pull/245 but it does solve the issue of creating the server too early so that code could be simplified now I believe. 
Thanks
=> refactor: set openapi server url as close to startup as possible

Makefile, examples/petstore/controllers/pets.go, examples/petstore/controllers/pets_test.go, examples/petstore/lib/testdata/doc/openapi.golden.json, option.go, option/option.go, option_test.go
to allow for setting or overriding of any routes status code
Could really decide whether I wanted to provide a constructor for `fuego.Response` pretty open on that. I did elect to not allow for variadic default of type for 400+ error codes as we discussed in some previous issues/MRs that we shouldn't assuming that all errors are `fuego.HTTPError`'s especially with the recent updates with Default Error Handler.
Also deprecation of AddError in favor of AddResponse.
=> feat: AddResponse 

examples/petstore/lib/testdata/doc/openapi.golden.json, mux.go, route.go, server_test.go
Allow to centralize the route object creation : less code duplication, usable from the Gin compat package, and also documented the Route object.
Not the most important PR to be honest, but it cleans the code and make it cleaner.
=> Refactor, mutualize and document Route object

examples/full-app-gourmet/server/server.go, examples/petstore/lib/server.go, examples/petstore/lib/testdata/doc/openapi.golden.json, examples/petstore/main.go, openapi.go, openapi_operations.go, openapi_operations_test.go, option.go, serve_test.go, server.go
Inspired by #274. 
- Changes `WithGlobalResponseType` to use `fuego.Response` as an input
- Defaults `WithGlobalResponseType` inputs to contain `application/json` and `application/xml` closes #247 
- Refactors `WithGlobalResponseType` to use the same helper as `OptionAddResponse` so we can stay in lock step with `fuego.Response` struct
Some notes: 
- I'm not the biggest fan of `openAPIResponse` for a struct name but it's just to hold the global response types until we get to generating the spec. Maybe `GlobalReponse` open to thoughts.
- thoughts on making `addResponseIfNotSet` a method
This was a fun PR. Looking forward to the feedback.
Cheers
=> BREAKING: update WithGlobalResponseType to take

server.go
Has been moved the the `OpenAPI` struct, just cleaning
=> Removes unused generator field from the Server struct

documentation/docs/guides/options.md, server.go, server_test.go
I figured it's time for this. It's been like 4 maybe 5 releases.
=> chore: remove previously deprecated WithPort

ctx.go, internal/common_context.go, openapi_operations.go, serve.go, server_test.go, validate_params.go
Tried to mutualize the Context so we will have less work to do for other integrations.
=> Mutualise a part of Context between net/http and gin

engine.go, server.go
As the title says.
It's not a lot haha, and we could have expected this, because we're really close to `net/http`. The next step will be to fit our Content-Negociation into this Engine. But we'll release the Gin compatibility package before as it's not the end if it only supports `application/json` for a few weeks.
=> Moved all non-net/http related code to the new Engine struct

mux.go, mux_test.go, openapi.go, option.go, option/option.go, server.go
Closes #270
This doesn't follow the theme of what #270 was saying but I believe it covers it. If we were to do `fuego.OptionShowInOpenAPI(bool)`. I say we should deprecate `OptionHide` in favor of use `fuego.OptionShowInOpenAPI(bool)`. 
Either way one hidden feature with this pull request is that it now allows for users to hide at the group level but also show a route in that group
=> Optionshow

option.go
My developer tools complain about this being deprecated when it isn't. Not sure if there is a better way to avoid this
=> chore: comment Deprecatd -> OptionDeprecated

ctx.go, ctx_test.go, internal/common_context.go, serve.go, serve_test.go
_Please look at the Pull Request in your IDE, the default Github diff is ugly._
This PR is made to make the previous Fuego `net/http` flow with validation, error handling... generic. It only uses Fuego's abstractions (the new `Engine`, `ContextWithBody`, and the good old fuego controller).
I will then move `flow` to internal and reuse it in the gin extension.
=> Generic main handler

deserialization.go, examples/gin-compat/main.go, extra/fuegogin/context.go
Adds the Transform and Validate capabilities of Fuego into the Gin adaptor
=> Transform and Validate Gin input

default_middlewares.go, examples/petstore/lib/testdata/doc/openapi.golden.json, go.mod, go.sum, openapi_operations_test.go, option_test.go, server.go, server_test.go
This PR implements a simplified default logging middleware, taking on feedback from #303.
These changes simplify #303 and just provides default req/res logging, with options to disable either. Rather than supporting custom logging functions, users who need custom logging can just implement their own mw.
I see some of these use cases:
1. Use default middleware entirely
2. Disable fully/partially disable req&res logging
3. Disable and implement their own logging middleware
4. Use our middleware but override logging funcs
After thinking about how to do this, supporting case 4 does seems unnecessary and more complex that it needs to be - for users needing custom logging it would be cleaner to just implement their own.
Note: Some tests are failing for now due to some golden files not expecting …
=> re-implementing default logging middleware

engine.go, engine_test.go, server.go
Moves WithErrorHandler to an engine option.
Closed #314 in favor of this as I created a mess over there.
=> BREAKING: WithErrorHandler server option to engine option

openapi.go
This pull requests wraps the errors on the `saveOpenAPIToFile(jsonSpecLocalPath string, jsonSpec []byte)` for better traceability and debugging 
Addresses this issue [321](https://github.com/go-fuego/fuego/issues/321)
=> chore: issue 321 (Wrap Errors where applicable)

.golangci.yml, Makefile, ctx.go, default_middlewares.go, engine.go, errors.go, html.go, internal/common_context.go, openapi_operations.go, option.go, perf.go, route.go, security.go, serve.go, server.go
Just a dumb PR to reduce memory usage and improve performance by simply realigning struct fields.  
I can't believe this has to be done manually—obviously, the compiler should handle it.  
This also enables all govet linters in the CI (including the `fieldalignment` check).  
We'll wait for #285 to see the improvement or lack thereof.
=> Optimize memory usage by reordering fields

engine.go, engine_test.go, openapi.go, option.go, option_test.go, route.go
Per @ccoVeille here https://github.com/go-fuego/fuego/pull/333#discussion_r1906016234
The naming here doesn't line up. I decided to follow the naming of fixed field `content` described here: https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-10.
=> refactor: change occurrences of A(a)cceptedContentTypes to R(r)equestContentTypes

errors.go, serialization.go, serialization_test.go, serve_test.go
closes #339
Based on #336 for readability.
=> fix: SendYAMLError to properly pass the entire error when sending

documentation/docs/guides/serialization.md
This pull request fixes the return type in the `echo` function to match the expected string type.
=> Fix return type in `echo` function to match expected string type

errors.go, serialization.go, serialization_test.go, serve_test.go
Per #322
The following is to test provide a bit easier of test bed for testing edge cases do to server misconfigs or poor user input. The test here will pass, but they bring up some questions:
1. When ErrorHandler is overridden there is a possibility it can return `nil` causing golang encode to eventually land on `null` (I will probably expand this to more return types but wanted to get the conversation going). What should we do here? Is the user setting the return type to nil to say it's fine and we should really respond with like `NoContent` or is just saying 500 with empty/null response good enough. I personally think if the user is setting their error to nil they're doing something on purpose 🤷 
2. In the case of transformOut error when it's receiver is a value and not a pointer. We …
=> chore: test Flow for edge cases cause by misconfigs

extra/fuegogin/adaptor.go
Same behaviour as in `net/http`
=> Gin supports default status code

engine.go, engine_test.go, extra/fuegogin/adaptor.go, net_http_mux.go, openapi.go, option.go, option_test.go, route.go, server.go, server_test.go
Relates to #333 
Somewhere along implementing support for different engines this was lost. This is a bit disruptive as it's changing the `NewRoute/NewBaseRoute`. The other option would be to place `acceptedContentTypes` on our `OpenAPI` struct I could go either way. We wouldn't be changing the `NewRoute` and `NewBaseRoute` API in the case of the later, but again we'd need to support yet another nested structure with it's own options. I think flattening in the Engine is OK, I guess 🤷.
So the options are
1. This PR. Just be fine with configuration occurring on the engine struct
2. Place `acceptedContentTypes` in the `OpenAPI` struct. We can could then do something like
```golang
func WithRequestContentType(consumes ...string) func(*Engine) {
return func(e *Engine) { …
```
=> fix: NewRoute/NewBaseRoute to take engine not just OpeAPI for accepted content types

.golangci.yml, ctx.go, engine.go, internal/common_context.go, multi_return.go, net_http_mux.go, openapi.go, option.go, option/option.go, param.go, security.go, serve.go, server.go, static/embed.go
- **chore: fix a lot of godoc**
- **chore: avoid redefining min/max**
- **chore: avoid unused parameter**
- **chore: use common receiver names**
- **chore: enable most of the default revive rules**
- **chore: enable most gocritic rules**
Motivation: I noticed some errors in the godoc, then I checked with revive and wow, so many things to fix
=> golangci party

extra/fuegoecho/adaptor.go, serve_test.go
Default status code for echo + formatting
=> Default status code for echo

engine.go, examples/gin-compat/adaptor_test.go, examples/gin-compat/handlers.go, examples/gin-compat/main.go, examples/petstore/lib/server_test.go, examples/petstore/lib/testdata/doc/openapi.golden.json, extra/fuegogin/adaptor.go, openapi.go, openapi_handler.go, openapi_handler_test.go, serve.go, server.go, server_test.go
Heavy WIP
Working through how this would work. 
Just wanted to get a initial outline on how we could do this. Feel free to discuss over top of this. I imagine we reach the point with our adaptors where we have something like `fuegogin.Adaptor.Run()`, in this case it would `engine.OutputOpenAPISpec`, `engine.RegisterOpenAPIRoutes`, and then start the gin server. Again everything is exposed and we can provide options maybe, but users can plug and play as they please. 
PS. Feel free to open PR against this or contribute directly 😄
=> WIP: OpenAPIServable

ctx.go, ctx_test.go, extra/fuegoecho/context.go, extra/fuegogin/context.go, go.work, mock_context.go
=> Path param int deserialization

default_middlewares.go
Removes the timestamp from the log lines, as it is already present in the log line itself.
Show Method and path first as it is the information the user is more likely to search for
=> Default logger easier to read

documentation/docs/tutorials/rendering/std.md
=> Use fuego.CtxRenderer in return type

openapi.go, openapi_test.go
Warning seen in #393. I think private fields tags shouldn't be processed, as they won't be seen outside anyway.
No link between the crashes in issue #393 and this warning.
=> feat: Silence unexported fields warning

examples/petstore/lib/testdata/doc/openapi.golden.json, examples/petstore/models/Pet.go
Following #394, I wanted to make sure the exception for the `time.Time` struct (declared like a string), actually [managed by kin](https://github.com/getkin/kin-openapi/blob/050a930912661dd1e1a955421d60d38d2f6dd5a3/openapi3gen/openapi3gen.go#L329), is fixed in Fuego.
=> Explicited time.Time behaviour for OpenAPI declaration

engine_test.go, errors.go, errors_test.go
I mentioned this in discord. Realized today that we can just expose the main logic for the default ErrorHandler and provide a function that always produces an HTTPError.
Cheers!
=> feat: expose HandleHTTPError for use WithErrorHandler option

errors.go, errors_test.go, server_test.go
If returning an error that was not HTTPError error in Fuego, it wasn't logged. Now it is.
=> feat: Log error even if not fuego.HTTPError

engine.go, serve.go, server_test.go
Hi!
I added the option to not automatically add a default open API server. If no servers are added Swagger UI will use the same host you are using to browse it. This means you can try the API on all the same hostnames you can see the documentation. I prefer it that way but can see not everyone does, therefore it's an opt-in setting.
=> option to disable default open api server

documentation/docs/guides/openapi.md
The current example code does not compile. It needs to be wrapped with `WithOpenAPIConfig` and the `OpenAPIConfig` parameters are out of date
=> docs: fix OpenApi Specification example code

default_middlewares.go
This PR allows users to use http.Flusher even with the wrapped http.ResponseWriter.
This was a regression since Fuego supported these before the http.ResponseWriter was wrapped.
=> feat: Support http.ResponseWriter options in the wrapper

engine_test.go, errors.go, errors_test.go, serialization.go, serialization_test.go, validation_test.go
This PR has several goals:
- avoid nil pointer dereference (`Error() string { return e.Err.Error() } ` panics when no e.Err. Happened a lot...
- have the same behaviour for `HTTPError` and other `XxxError`s
- Errors are formatted like `404 User Not Found (User 100 not in DB): sql: no rows in result set`
- Error will be sent to user as `404 User Not Found (User 100 not in DB)` if HTML or text
- When using `HTTPError` or variants, hide `e.Err` from being sent to the clients for security measures
- Use `e.Title`, `e.Details` and `e.Errors` to give informations to the clients
=> feat: Unify HTTP errors and improve error messages

default_middlewares.go, option.go, option/option.go, option_test.go, server.go, server_test.go
closes #366
Add the ability for a user to implicitly strip all slashes from all routes as well as strip all ending slashes from all requests at the fuego Server level.
This PR only makes this configurable at the level of the Server. This does come with a utility function to be able to configure path stripping at the route level but it's not incredibly useful (our uses should just do this themselves when they declare the path). 
Let me know what you think. It may be worth make that option private as it's not really useful unless you're stripping at the global level.
=> feat: add Server option of WithStripTrailingSlash

default_middlewares.go, default_middlewares_test.go
Closes #439 
- Protects against a panic in the case where ResponseWriter.Flush is not implemented
- Logs a warn message if flush is not implemented
=> fix: skip calling Flush on responseWriter when it is not implemented

extra/fuegogin/adaptor.go, extra/fuegogin/adaptor_test.go
This allows users of fuegogin to use the gin path format, while still generating the correct spec and allowing options like `fuego.OptionPath`.
Closes #448
=> allow use of gin path format

extra/fuegoecho/context.go, extra/fuegogin/context.go
Relates to #375
Echo is actually writing `text/plain` for all responses not even in cases where we set Default status code is used. This fixes it for both cases. Leaving only fuego with the default status code bug. Gin actually works to do it's set status helper
Note: should we update the `DefaultStatusCode` comment docs to state that this option does not work with fuego Server?
Another note: I can't really provide a test on this besides for some pics as we don't have a e2e test. `httptest.ResponseWriter` implementation allows for the header to be overwritten through the test. I think this raises for #360 to be opened 🫤 sorry about not being clear on my original concerns.
Here is the echo server before and after btw:
before: 
After:
I know we like tests but this is pretty significant, and …
=> fix: default status code for echo

engine.go, server_test.go
Noticed that this property wasn't being passed through when I configured the fuego instance.
=> fix: allow setting disable messages from openapi config

ctx.go, ctx_test.go, internal/common_context.go
Indirectly closes my concerns with #386 and could make #419 unneeded.
```
PathParamNotFoundError
PathParamInvalidTypeError
QueryParamNotFoundError
QueryParamInvalidTypeError
```
All to adhere to the interfaces of `ErrorWithStatus` and `ErrorWithDetail`. In our default errorhandler in the case of the implementation of `ErrorWithStatus` we cast the error to HTTPError anyway. This will also expose the error as Detail ensure we're returning. 
Let me know what you guys think. I don't see the point of copying HTTPError into common Context just to support in both places when we can just implement the interface. See this comment for some context on that: https://github.com/go-fuego/fuego/pull/419#discussion_r1975070317. I did work my way through half this solution before I realized we could just …
=> fix: add detail/status for queryparam errs and detail for path errs

openapi.go, openapi_test.go
Allow non-.json paths for OpenAPI specs, for example:
```go
s := fuego.NewServer(
fuego.WithEngineOptions(
fuego.WithOpenAPIConfig(fuego.OpenAPIConfig{
SpecURL:          "/api-specs",  // no .json needed
}),
),
)
```
The mandatory ".json" extension has been removed, allowing paths like `/openapi`, `/api-specs`, or `/specs` without an error message. Now by default I still get json, but if I use the "accept: application/yaml" I can get the yaml specs. Btw, it is weird to use a non-json "accept" on a .json endpoint.
**I do this PR on the main branch, is that meant to be?**
`make ci` gave me test failures right after the cloning the `main`:
- `FAIL    github.com/go-fuego/fuego       1.781s`
- `FAIL    github.com/go-fuego/fuego/extra/sqlite3 [build failed]`
I tired on ubuntu & macos, go …
=> feat: Allow non-.json paths for OpenAPI specs

deserialization.go, engine.go, engine_test.go, errors.go, errors_test.go, internal/common_context.go, serialization.go, serialization_test.go, serve.go, serve_test.go
Closes: #496 
BREAKING CHANGE: `ErrorHandler` signature is updated to also include context. 
This change allows callers too pass request scoped values to our log functions. The great thing about slog is that it allows you to bring your own logger. Slog even suggest to use [context functions](https://pkg.go.dev/log/slog#hdr-Contexts) when possible for this very reason. 
> It is recommended to pass a context to an output method if one is available.
Thanks
=> BREAKING: use slog.***Context where applicable 

openapi.go, openapi_test.go
At the struct name as a field. Couldn't really tell what structures it's referring too unless we have the struct name.
=> fix: add struct to log property not found log when parsing structTags

documentation/docs/guides/openapi.md
The docs custom ui example did not work with the latest fuego version because of a version mismatch of the openapi specs.
More here: https://github.com/go-fuego/fuego/issues/579
=> Fix custom ui example in docs
